[platformio]
default_envs = esp32c3_supermini
build_dir = build/pio

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  mikalhart/TinyGPSPlus @ ^1.1.0
build_flags =
  -D SERIAL_BAUD=115200
  -D CORE_DEBUG_LEVEL=0
  -D SAMPLE_INTERVAL_MS=5000
  -D TMP117_ADDR=0x48
  -D MAX30102_ADDR=0x57

[env:esp32dev]
board = esp32dev
build_flags =
  ${env.build_flags}
  -D I2C_SDA_PIN=21
  -D I2C_SCL_PIN=22
  -D LTE_RX_PIN=16
  -D LTE_TX_PIN=17
  -D BUZZER_PIN=25

[env:xiao_esp32c3]
board = seeed_xiao_esp32c3
build_flags =
  ${env.build_flags}
  -D I2C_SDA_PIN=6
  -D I2C_SCL_PIN=7
  -D LTE_RX_PIN=20
  -D LTE_TX_PIN=21
  -D BUZZER_PIN=10
  -D LTE_PWRK_PIN=5
  -D TEST_TRIGGER_PIN=4
  -D ENABLE_STATE_BUZZER=0

[env:esp32c3_supermini]
board = esp32-c3-devkitm-1
build_flags =
  ${env.build_flags}
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D I2C_SDA_PIN=8
  -D I2C_SCL_PIN=9
  -D LTE_RX_PIN=20
  -D LTE_TX_PIN=21
  -D GPS_RX_PIN=6
  -D GPS_TX_PIN=7
  -D GPS_BAUD=115200
  -D BUZZER_PIN=10
  -D TEST_TRIGGER_PIN=4
  -D BATTERY_TEST_PIN=5
  -D ENABLE_STATE_BUZZER=0
